/* 
 * File:   mcal_interrupt_gen_config.h
 * Author: MOUSTAFA
 *
 * Created on February 28, 2023, 5:32 AM
 */

#ifndef MCAL_INTERRUPT_GEN_CONFIG_H
#define	MCAL_INTERRUPT_GEN_CONFIG_H

#define INTERRUPT_FREATUERE_ENABLE  1U

//#define INTERRUPT_PRIORITY_LEVELS  INTERRUPT_FREATUERE_ENABLE
#define TIMER0_INTERRUPT_FEATURE      INTERRUPT_FREATUERE_ENABLE
#define TIMER1_INTERRUPT_FEATURE      INTERRUPT_FREATUERE_ENABLE
#endif	/* MCAL_INTERRUPT_GEN_CONFIG_H */

